name: Technoruler 
description: Blogging about mobile API's and random fav things
meta_description: "IamVP7 blogging website who blogs about Mobile application API's and his workshop experience"
gems: [jekyll-paginate, jekyll-gist]
aboutPage: true

highlighter: rouge

paginate: 5
paginate_path: "page:num"
baseurl: /
domain_name: 'http://iamVP7.github.io/'
google_analytics: 'UA-69083735-1'
disqus: true
disqus_shortname: 'iamvp7'

# Details for the RSS feed generator
url:            'http://iamVP7.github.io/'
author:         'IamVP7'
authorTwitter:  'IamVP7'

permalink:       /:year/:month/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
